# Generated by Django 4.1.1 on 2022-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0002_alter_directory_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Directory',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='Directory',
            name='path',
            field=models.FilePathField(allow_folders=True, default=['/home/ethan_tregidga/PycharmProjects/Nicer_Website/static'], path=['/home/ethan_tregidga/PycharmProjects/Nicer_Website/static']),
        ),
        migrations.AddField(
            model_name='Directory',
            name='type',
            field=models.CharField(choices=[('dir', 'Directory'), ('file', 'File')], default='dir', max_length=4),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
