# Generated by Django 4.1.1 on 2022-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0003_remove_directory_parent_id_directory_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Directory',
            name='path',
            field=models.FilePathField(allow_folders=True, default='/home/ethan_tregidga/PycharmProjects/Nicer_Website/static', path='/nicer_website/static'),
        ),
    ]
