# Generated by Django 4.1.1 on 2022-09-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0004_alter_directory_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Item',
        ),
    ]
