# Generated by Django 4.1.1 on 2022-09-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0005_rename_file_mgr_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
