# Generated by Django 4.1.1 on 2022-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0010_alter_item_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.CharField(default='root', max_length=100),
        ),
    ]
