# Generated by Django 4.1.1 on 2022-09-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0014_alter_item_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'path', 'type'), name='unique_name_path_type'),
        ),
    ]
