# Generated by Django 4.1.1 on 2022-09-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0018_remove_item_unique_name_path_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_name_path_type',
        ),
    ]
