# Generated by Django 4.1.1 on 2022-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0019_remove_item_unique_name_path_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'path', 'type'), name='unique_name_path_type'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('path__isnull', True)), fields=('name', 'type'), name='unique_name_type'),
        ),
    ]
