# Generated by Django 4.1.1 on 2022-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0020_item_unique_name_path_type_item_unique_name_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['path'], name='path_idx'),
        ),
    ]
