# Generated by Django 4.1.1 on 2023-01-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0021_item_path_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_name_type',
        ),
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
