# Generated by Django 4.1.1 on 2023-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0022_remove_item_unique_name_type_alter_item_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
    ]
