# Generated by Django 4.1.1 on 2023-01-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0023_item_type_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='type_idx',
        ),
    ]
