# Generated by Django 4.1.1 on 2023-01-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0024_remove_item_type_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
    ]
