# Generated by Django 4.1.1 on 2023-01-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0025_item_type_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='type_idx',
        ),
    ]
